version: '3' 
services: 
  node:     
    build: .
    ports: 
      - 4000:4000 
    volumes:
      - .:/app
    environment:
      REDIS_HOST: redis
    depends_on: 
      - redis
      - postgresql
    networks: 
      - server
      - database
      - redis
  postgresql: 
    image: postgres
    restart: always
    volumes:
      - postgre_data:/var/lib/postgresql/data
    networks: 
      - database
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on: 
      - postgresql
    networks: 
      - database
  redis:
    image: redis
    networks: 
      - redis
volumes:
  postgre_data:
networks:
  server:
  database:
  redis: