//CONTACTS
export const SET_CURRENT_CONTACT = 'SET_CURRENT_CONTACT';
export const LOAD_CONTACTS_SUCCESS = 'LOAD_CONTACTS_SUCCESS';
export const CONTACT_ADD = 'CONTACT_ADD';
export const CONTACT_UPDATE = 'CONTACT_UPDATE';

//CHAT
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const FETCH_MESSAGES = 'FETCH_MESSAGES';
export const FETCH_MESSAGES_SUCCESS = 'FETCH_MESSAGES_SUCCESS';

//USER
export const USER_IS_SIGN_IN = 'USER_IS_LOGGING';
export const USER_SIGN_IN_SUCCESS = 'USER_SIGN_IN_SUCCESS';
export const USER_SIGN_IN_ERROR = 'USER_SIGN_IN_ERROR';
export const USER_IS_SIGN_OUT = 'USER_IS_SIGN_OUT';
export const USER_SIGN_OUT_SUCCESS = 'USER_SIGN_OUT_SUCCESS';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_ERROR = 'USER_REGISTER_ERROR';