//CONTACTS
export const SET_CURRENT_CONTACT = 'SET_CURRENT_CONTACT';
export const LOAD_CONTACTS = 'LOAD_CONTACTS';
export const CONTACT_ADD = 'CONTACT_ADD';
export const CONTACT_UPDATE = 'CONTACT_UPDATE';

//CHAT
export const FETCH_MESSAGES = 'FETCH_MESSAGES';
export const FETCH_MESSAGES_SUCCESS = 'FETCH_MESSAGES_SUCCESS';

//USER
export const LOGIN = 'LOGIN';

export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_ERROR = 'SIGN_UP_ERROR';
export const SIGN_OUT_REQUEST = 'SIGN_OUT_REQUEST';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const SIGN_OUT_ERROR = 'SIGN_UP_ERROR';